#
# Camunda - Latest
#

global:
  # https://github.com/camunda/camunda-platform/releases
  # https://hub.docker.com/u/camunda
  image:
    # renovate: datasource=docker depName=camunda/zeebe
    tag: 8.2.19

zeebe:
  # https://github.com/camunda/zeebe/releases
  # https://hub.docker.com/r/camunda/zeebe
  image:
    # renovate: datasource=docker depName=camunda/zeebe
    tag: 8.2.19
    
operate:
  # https://github.com/camunda/operate/releases
  # https://hub.docker.com/r/camunda/operate
  image:
    # renovate: datasource=docker depName=camunda/operate
    tag: 8.2.19

tasklist:
  # https://github.com/camunda/tasklist/blob/master/CHANGELOG.md
  # https://hub.docker.com/r/camunda/tasklist
  image:
    # renovate: datasource=docker depName=camunda/tasklist
    tag: 8.2.19

connectors:
  # https://hub.docker.com/r/camunda/connectors-bundle/tags
  image:
    repository: camunda/connectors-bundle
    tag: 0.23.2

identity:
  # https://github.com/camunda-cloud/identity/releases
  # https://hub.docker.com/r/camunda/identity
  image:
    # renovate: datasource=docker depName=camunda/identity
    tag: 8.2.19

  keycloak:
    # https://hub.docker.com/r/bitnami/keycloak/tags
    image:
      repository: bitnami/keycloak
      tag: 19.0.3
    postgresql:
      # https://hub.docker.com/r/bitnami/postgresql/tags
      image:
        repository: bitnami/postgresql
        tag: 15.4.0

optimize:
  # https://hub.docker.com/r/camunda/optimize/tags
  image:
    repository: camunda/optimize
    tag: 3.10.6

webModeler:
  # Camunda Enterprise repository.
  # registry.camunda.cloud/web-modeler-ee
  image:
    # renovate: datasource=docker depName=camunda/web-modeler lookupName=registry.camunda.cloud/web-modeler-ee/modeler-restapi
    tag: 8.2.9

#
# Elasticsearch
#

elasticsearch:
  # https://hub.docker.com/r/elastic/elasticsearch/tags
  image: docker.elastic.co/elasticsearch/elasticsearch
  # renovate: datasource=docker depName=elasticsearch/elasticsearch lookupName=docker.elastic.co/elasticsearch/elasticsearch
  imageTag: 7.17.16

retentionPolicy:
  # https://hub.docker.com/r/bitnami/elasticsearch-curator/tags
  image:
    repository: bitnami/elasticsearch-curator-archived
    tag: 5.8.4
